### ISSUE TITLE
Undocumented (?) message

### ISSUE THREAD

**Issue by aubertc** [debian-tex/latexmk#10]
I use (pandoc, but I don't think that's the point, and) latexmk to compile a file, and I obtain the following error / warning message:

> `Latexmk: In reading rule 'xdvipdfmx' in 'aux/input.fdb_latexmk',`
>         `name of destination file is not current one; I'll flag rule as out of date.`

I could not find any explanation or comment on this message in latexmk's documentation.

The (relevant bits of the) command I use is

```
pandoc \
  --pdf-engine=latexmk \
  --pdf-engine-opt=-bibtex --pdf-engine-opt=-pdfxe \
  --pdf-engine-opt=-emulate-aux-dir --pdf-engine-opt=-aux-directory=aux  \
  --biblatex main.md -o main.pdf
```

so that the options passed to latexmk are "`-bibtex -pdfxe -emulate-aux-dir -aux-directory=aux`".

I am using `Latexmk, John Collins, 21 September 2021. Version 4.75`, and it seems that this message is commented as follows in the source code:

```
# Deal with possibility that destination in fdb_latexmk has different name
# than the default one.  The only case that concerns us is where
# the extension is changed (by \pdfoutput, e.g., in tex file).  But
# it is possible out and aux directories have been chosen differently,
# and the user choice there MUST OVERRIDE the value in the fdb_latexmk file.
```

Is latexmk complaining that the name of the pdf file and of the source (tex) files are not matching?

**Comment by norbusan** [comment]
Sorry, this is purely a question of upstream latexmk and has no relation to the Debian packaging, thus I am closing this issue. Please contact upstream with these questions. Thanks
