### ISSUE TITLE
.fdb_latexmk files are not source-control friendly

### ISSUE THREAD

**Issue by bersbersbers** [debian-tex/latexmk#9]
Some of my `tex` files take *very* long to compile, so I commit the `.fdb_latexmk` files to a git repository. It would be great if the final files (after `latexmk` has finished) could be made idempotent (that is, running `latexmk` again on the same files, with `latexmk` deciding that "All targets are up to date", should generate the same file). There's two parts to that.

One is the timestamps - I am not sure this can be solved. But since I can usually re-use the previous `.fdb_latexmk` files, the exact timestamps in these files do not seem to matter much. Maybe in an optional source-control-friendly mode, these timestamps could be excluded.

The other is the order of files, which for some reason varies between subsequent runs:
![image](https://user-images.githubusercontent.com/12128514/132873590-1f916ee7-8eea-4b3e-a32e-5fe48527d7e2.png)

**Comment by norbusan** [comment]
No Debian issue, please discuss with upstream. Closing this issue
